# Generated by Django 5.1.7 on 2025-03-22 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.TextField()),
                ('book_path', models.CharField(max_length=250)),
                ('book_author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.authors')),
            ],
        ),
    ]
