# Generated by Django 5.1.7 on 2025-03-22 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='book_genre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.genres'),
        ),
    ]
