# Generated by Django 5.1.7 on 2025-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_genres_books_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='book_path',
        ),
        migrations.AddField(
            model_name='books',
            name='book_path_en',
            field=models.CharField(default='/books/en', max_length=250),
        ),
        migrations.AddField(
            model_name='books',
            name='book_path_ru',
            field=models.CharField(default='/books/ru', max_length=250),
        ),
    ]
