# Generated by Django 5.1.7 on 2025-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_books_book_path_books_book_path_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_cover',
            field=models.ImageField(blank=True, default='books_cover.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_path_en',
            field=models.CharField(default='/books/adventures/en', max_length=400),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_path_ru',
            field=models.CharField(default='/books/adventures/ru', max_length=400),
        ),
    ]
