# Generated by Django 5.1.7 on 2025-03-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_books_book_cover_alter_books_book_path_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='book_description',
            field=models.TextField(default='Not found!', null=True),
        ),
    ]
